spring:
  application:
    name: auth-server-java
  security:
    user:
      name: sally
      password: password
    oauth2:
      authorizationserver:
        client:
          test-client:
            registration:
              client-id: test-client
              client-secret: "{noop}secret"
              client-authentication-methods:
                - none
              authorization-grant-types:
                - authorization_code
                - refresh_token
              scopes:
                - user.read
              redirect-uris:
                - http://localhost:3000/callback
          token-client:
            registration:
              client-id: token-client
              client-secret: "{noop}token"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - urn:ietf:params:oauth:grant-type:token-exchange
              scopes:
                - message.read
